//! Lester, [Victor]’s cousin, makes raster graphics.
//!
//! This is a reimplementation of [Poppler]’s `pdftocairo` utility program as a Rust library.
//! It loads PDF documents with Poppler
//! and renders (rasterizes) them to in-memory pixel buffers with [cairo].
//! It can then export to PNG.
//!
//! Lester is primarily intended to help test the visual rendering of PDF files generated by Victor.
//! Reimplementing `pdftocairo` enables skipping the overhead of cross-process communication
//! and image compression/decompression.
//! It will also enable extracting (and testing) PDF metadata at the same time as rendering.
//!
//!
//! ## Requirements
//!
//! * [Poppler], with its `glib` wrapper API.
//! * [cairo]
//! * [pkg-config], at build time
//!
//!
//! [Victor]: https://github.com/SimonSapin/victor
//! [Poppler]: https://poppler.freedesktop.org/
//! [cairo]: https://www.cairographics.org/
//! [pkg-config]: https://www.freedesktop.org/wiki/Software/pkg-config/

mod cairo_ffi;  // Not re-exported
mod poppler_ffi;  // Not re-exported
mod errors;
mod cairo;
mod poppler;

pub use errors::*;
pub use cairo::*;
pub use poppler::*;
