[package]
name = "victor"
version = "0.0.1"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT OR Apache-2.0"
description = "Victor makes vectors"
repository = "https://github.com/SimonSapin/victor"

[lib]
test = false
doctest = false

[dependencies]
euclid = "0.15.4"
lazy_static = "0.2"
lopdf = "0.14.1"
opentype = {git = "https://github.com/bodoni/opentype", rev = "693c8d93247273a6d4baf4cc2ef01e246fceb829"}
